#YamlPropertySourceLoader 会将application.yml的属性通过PropertySource导入到Environment上下文
server:
  port: 8080

#日志配置文件位置
logging:
  config: classpath:log/log4j2.xml

spring:
  profiles:
    active: local
  mvc:
    favicon:
      enabled: false
  aop:
    proxy-target-class: true

## mybatis 之 org.mybatis.spring.SqlSessionFactoryBean 属性 : mybatis-spring
#mybatis:
#  configuration:
#    cache-enabled: false
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: false
#    map-underscore-to-camel-case: true
#    default-statement-timeout: 2000
#    use-generated-keys: true
#    call-setters-on-nulls: true
#    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#
##pagehelper
#pagehelper:
#  offset-as-page-num: false
#  row-bounds-with-count: true
#  page-size-zero: true
#  reasonable: false   #禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
#  support-methods-arguments: false

